export const TYPE_PLAYER = 'TYPE_PLAYER';
export const TYPE_ENEMY_CAR = 'TYPE_ENEMY_CAR';
export const DEFAULT_PLAYER_COLOR = 0xF62C1B;

export const CAR_COLORS = [
  0x2F2E38,
  0x708323,
  0x5A7D83,
  0x6482F0
]

export const GAME_STATE_MENU = 'GAME_STATE_MENU';
export const GAME_STATE_PLAY = 'GAME_STATE_PLAY';
export const GAME_STATE_END = 'GAME_STATE_END';